### ISSUE TITLE
Why does Aggregate::State require Default + Clone?

### ISSUE THREAD

**Issue by angelo-rendina-prima** [primait/event_sourcing.rs#159]
Imho it's wrong and both traits should be removed.
1. `Clone`: the state should be derived from the events i.e. `load`ed from the store. Allowing you to clone it just escalates the chance a concurrent system emits new events while you hold a cloned state, and cause issues (with either optimistic or pessimist locking).
2. `Default`: the state of affairs is that we are forced to define a `#[default] EmptyState` variant that adds little value. Can't we just use `None` as the default state and `Some(_)` for an actual, non-default state? What are some use cases for having an instantiated non-empty fallback state? Anything in there can be defined as constants somewhere else. Does it complicate the API too much?
Related to this, when I `load` an aggregate state, what distinguish a `None` from a Some(#[default] EmptyState)`? They are functionally identical, right?

**Comment by cottinisimone** [comment]
Ehy Angelo.

Totally fine for the `Clone` trait, it is an unnecessary bound put on the aggregate state. About the `Default` it is necessary when rebuilding the state, being that while `loading` you need to start from a brand new state on which you apply all the events in the event store. No clue on how to do it otherwise. Do you have any suggestion?

Regarding this comment:

> Related to this, when I load an aggregate state, what distinguish a None from a Some(#[default] EmptyState)`? They are functionally identical, right?

The difference is that receiving a `None` means that that aggregate does not exist, while a `Some(#[default] EmptyState)` could be an aggregate that exists but it's actual events do not modify its state and so the result of the `load` it's his default. I think anyway that might be worth it to document it a bit more and left an unclear concept to library users.
